### ISSUE TITLE
Cannot edit config of OVS by of-config

### ISSUE THREAD

**Issue by budnyjj** [openvswitch/of-config#3]
Hello!
I'm trying to setup configuration of openvswitch with Ryu of_config library:

``` python
from ryu.base import app_manager
from ryu.lib import hub
from ryu.lib.of_config import capable_switch

HOST = '127.0.0.1'
PORT = 830
USERNAME = 'of-config'
PASSWORD = 'password'

class OFConfigClient(app_manager.RyuApp):
        def __init__(self, *args, **kwargs):
                super(OFConfigClient, self).__init__(*args, **kwargs)
                self.switch = capable_switch.OFCapableSwitch(
                        host=HOST, port=PORT, username=USERNAME, password=PASSWORD,
                        unknown_host_cb=lambda host, fingerprint: True)

        def get_set(self):
                csw = self.switch.get_config('running')
                self.switch.edit_config('running', csw)

if __name__ == '__main__':
        client = OFConfigClient()
        client.get_set()
```

This script get configuration from OVS by using of-config and set it back in unchanged state.
When I run it, I get this traceback:

```
Traceback (most recent call last):
  File "test_ovs_ofconfig.py", line 23, in <module>
    client.get_set()
  File "test_ovs_ofconfig.py", line 19, in get_set
    self.switch.edit_config('running', csw)
  File "/usr/local/lib/python2.7/dist-packages/ryu/lib/of_config/capable_switch.py", line 118, in edit_config
    self.raw_edit_config(target, xml, default_operation)
  File "/usr/local/lib/python2.7/dist-packages/ryu/lib/of_config/capable_switch.py", line 108, in raw_edit_config
    default_operation, test_option, error_option)
  File "/usr/local/lib/python2.7/dist-packages/ryu/contrib/ncclient/manager.py", line 78, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/ryu/contrib/ncclient/manager.py", line 132, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/ryu/contrib/ncclient/operations/edit.py", line 58, in request
    return self._request(node)
  File "/usr/local/lib/python2.7/dist-packages/ryu/contrib/ncclient/operations/rpc.py", line 289, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: Some unspecified error occurred.
```

Simple reading of configuration works just fine.

**Comment by rkrejci** [comment]
Hi, what is the content of the datastore? I mean, what is stored in csw after self.switch.get_config('running') and then put to the self.switch.edit_config('running', csw)?

**Comment by budnyjj** [comment]
csw == 

``` python
OFCapableSwitchType(
  config_version=None,
  configuration_points=None,
  id='openvswitch',
  logical_switches=OFCapableSwitchLogicalSwitchesType(
    switch=[
      OFLogicalSwitchType(
        capabilities=None,
        check_controller_certificate=None,
        controllers=None,
        datapath_id='00:01:02:03:04:05:06:07',
        enabled=None,
        id='ofc-bridge',
        lost_connection_behavior='failSecureMode',
        resources=OFLogicalSwitchResourcesType(
          certificate=None,
          flow_table=[],
          port=['ofc-bridge'],
          queue=[]
        )
      )
    ]
  ),
  resources=OFCapableSwitchResourcesType(
    external_certificate=[],
    flow_table=[],
    owned_certificate=[],
    port=[
      OFPortType(
        configuration=OFPortConfigurationType(
          admin_state='down',
          no_forward=None,
          no_packet_in=None,
          no_receive=None
        ),
        current_rate=None,
        features=None,
        max_rate=None,
        name='ofc-bridge',
        number=None,
        resource_id=None,
        state=None,
        tunnel_type=None
      )
    ],
    queue=[]
  )
)
```

I also get these messages from time to time:

```
ofc-server[2543]: OpenFlow: ofc-bridge is not a bridge or a socket.
ofc-server[2543]: OpenFlow: could not connect to 'ofc-bridge' bridge.
```

But ofc-bridge in connected to ovs:

``` bash
# ovs-vsctl show
e16e8912-c245-4a3b-9a2f-3ac27bbf9887
    Bridge ofc-bridge
        fail_mode: secure
        Port ofc-bridge
            Interface ofc-bridge
                type: internal

# ip addr
...
10: ofc-bridge: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default 
    link/ether 4a:b4:cf:66:4e:44 brd ff:ff:ff:ff:ff:ff
```

**Comment by rkrejci** [comment]
ryu supports OF-CONFIG 1.1.1, but this project implements OF-CONFIG 1.2. In the edit-config, ryu sends data in 1.1.1 namespace (see below) so it is not recognised by the server as data applicable to the datastore. I have improved the message you are receiving so it should be more clear for users now.

``` xml
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" 
    xmlns:ns1="urn:onf:of111:config:yang"
    xmlns:ns2="urn:onf:config:yang"
    message-id="urn:uuid:ec184cfe-d15c-11e4-b9f7-08002766f284">
  <nc:edit-config>
    <nc:target>
      <nc:running/>
    </nc:target>
    <nc:config>
      <ns1:capable-switch>
        <ns2:id>openvswitch</ns2:id>
        <ns1:resources>
          <ns1:port>
            <ns2:name>ofc-bridge</ns2:name>
            <ns1:configuration>
              <ns2:admin-state>down</ns2:admin-state>
              <ns2:no-receive>false</ns2:no-receive>
              <ns2:no-forward>false</ns2:no-forward>
              <ns2:no-packet-in>false</ns2:no-packet-in>
            </ns1:configuration>
          </ns1:port>
        </ns1:resources>
        <ns1:logical-switches>
          <ns1:switch>
            <ns2:id>ofc-bridge</ns2:id>
            <ns2:datapath-id>00:01:02:03:04:05:06:07</ns2:datapath-id>
            <ns2:lost-connection-behavior>failSecureMode</ns2:lost-connection-behavior>
            <ns1:resources>
              <ns2:port>ofc-bridge</ns2:port>
            </ns1:resources>
          </ns1:switch>
        </ns1:logical-switches>
      </ns1:capable-switch>
    </nc:config>
  </nc:edit-config>
</nc:rpc>
```
